'use client';

import { Card, CardContent } from '@/components/ui/card';
import { Lock, Eye, Shield, Database, Globe, UserCheck, Bell, Settings, Mail, Cookie, Server, Users, FileText, AlertCircle, Info } from 'lucide-react';
import Link from 'next/link';

export default function PrivacyPolicyPage() {
  const definitions = [
    {
      term: 'Cookie',
      definition: 'Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.'
    },
    {
      term: 'Company',
      definition: 'When this policy mentions "Company," "we," "us," or "our," it refers to Tournest, Abuja, that is responsible for your information under this Privacy Policy.'
    },
    {
      term: 'Country',
      definition: 'Where Tournest or the owners/founders of Tournest are based, in this case is Nigeria.'
    },
    {
      term: 'Customer',
      definition: 'Refers to the company, organization or person that signs up to use the Tournest Service to manage the relationships with your consumers or service users.'
    },
    {
      term: 'Device',
      definition: 'Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Tournest and use the services.'
    },
    {
      term: 'IP Address',
      definition: 'Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks.'
    },
    {
      term: 'Personal Data',
      definition: 'Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.'
    },
    {
      term: 'Service',
      definition: 'Refers to the service provided by Tournest/ShowStakr as described in the relative terms and on this platform.'
    },
    {
      term: 'Website',
      definition: 'Tournest\'s site, which can be accessed via this URL: tournest.io and showstakr.tournest.io'
    }
  ];

  return (
    <div className='min-h-screen bg-black'>
      {/* Background Effects */}
      <div className='fixed inset-0 bg-gradient-to-br from-violet-950/20 via-black to-pink-950/20' />
      <div className='fixed inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-purple-900/10 via-transparent to-transparent' />

      <div className='relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16'>
        {/* Header */}
        <div className='text-center mb-12'>
          <div className='inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-violet-500 to-pink-500 mb-6'>
            <Lock className='w-8 h-8 text-white' />
          </div>
          <h1 className='text-4xl sm:text-5xl font-black mb-4'>
            <span className='bg-gradient-to-r from-violet-400 via-pink-400 to-orange-400 bg-clip-text text-transparent'>
              Privacy Policy
            </span>
          </h1>
          <p className='text-gray-400 text-lg'>
            Last updated: January 1, 2025
          </p>
        </div>

        {/* Introduction */}
        <Card className='bg-gradient-to-br from-violet-900/30 to-pink-900/30 border-white/10 mb-8'>
          <CardContent className='p-8'>
            <h2 className='text-2xl font-bold text-white mb-4'>Our Commitment to Privacy</h2>
            <p className='text-gray-300 mb-4'>
              Tournest (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. 
              This Privacy Policy explains how your personal information is collected, used, and disclosed by Tournest 
              and its service ShowStakr.
            </p>
            <p className='text-gray-300'>
              This Privacy Policy applies to our website, and its associated subdomains (collectively, our &quot;Service&quot;) 
              alongside our application, ShowStakr. By accessing or using our Service, you signify that you have read, 
              understood, and agree to our collection, storage, use, and disclosure of your personal information as 
              described in this Privacy Policy and our Terms of Service.
            </p>
          </CardContent>
        </Card>

        {/* Definitions and Key Terms */}
        <Card className='bg-white/5 backdrop-blur-sm border-white/10 mb-8'>
          <CardContent className='p-8'>
            <div className='flex items-center gap-3 mb-6'>
              <FileText className='w-6 h-6 text-violet-400' />
              <h2 className='text-2xl font-bold text-white'>Definitions and Key Terms</h2>
            </div>
            <p className='text-gray-400 mb-6'>
              To help explain things as clearly as possible in this Privacy Policy, these terms are strictly defined as:
            </p>
            <div className='space-y-4'>
              {definitions.map((item, index) => (
                <div key={index} className='p-4 rounded-xl bg-black/30 border border-white/5'>
                  <h3 className='text-violet-400 font-semibold mb-2'>{item.term}:</h3>
                  <p className='text-gray-400 text-sm'>{item.definition}</p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Information We Collect */}
        <Card className='bg-white/5 backdrop-blur-sm border-white/10 mb-8'>
          <CardContent className='p-8'>
            <div className='flex items-start gap-4'>
              <Database className='w-6 h-6 text-violet-400 flex-shrink-0 mt-1' />
              <div className='flex-1'>
                <h2 className='text-2xl font-bold text-white mb-4'>What Information Do We Collect?</h2>
                <p className='text-gray-400 mb-4'>
                  We collect information from you when you visit our website, register on our site, place an order, 
                  subscribe to our newsletter, respond to a survey or fill out a form.
                </p>
                <ul className='space-y-2'>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>Name / Username</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>Phone Numbers</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>Email Addresses</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>Password (encrypted)</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>Transaction and payment information</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>Usage data and analytics</span>
                  </li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* How We Use Information */}
        <Card className='bg-white/5 backdrop-blur-sm border-white/10 mb-8'>
          <CardContent className='p-8'>
            <div className='flex items-start gap-4'>
              <Eye className='w-6 h-6 text-violet-400 flex-shrink-0 mt-1' />
              <div className='flex-1'>
                <h2 className='text-2xl font-bold text-white mb-4'>How Do We Use The Information We Collect?</h2>
                <p className='text-gray-400 mb-4'>
                  Any of the information we collect from you may be used in one of the following ways:
                </p>
                <ul className='space-y-3'>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>To personalize your experience (your information helps us to better respond to your individual needs)</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>To process transactions</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>To administer a contest, promotion, survey or other site feature</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-violet-400 mt-1'>•</span>
                    <span className='text-gray-300'>To send periodic emails and notifications</span>
                  </li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Information Sharing */}
        <Card className='bg-white/5 backdrop-blur-sm border-white/10 mb-8'>
          <CardContent className='p-8'>
            <div className='flex items-start gap-4'>
              <Globe className='w-6 h-6 text-violet-400 flex-shrink-0 mt-1' />
              <div className='flex-1'>
                <h2 className='text-2xl font-bold text-white mb-4'>Do We Share Information With Third Parties?</h2>
                <p className='text-gray-400 mb-4'>
                  We may share the information that we collect, both personal and non-personal, with third parties such as 
                  advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or 
                  whose products or services we think may interest you.
                </p>
                <p className='text-gray-400 mb-4'>
                  We may engage trusted third party service providers to perform functions and provide services to us, such as:
                </p>
                <ul className='space-y-2 text-gray-300'>
                  <li>• Hosting and maintaining our servers and the website</li>
                  <li>• Database storage and management</li>
                  <li>• Email management</li>
                  <li>• Payment processing</li>
                  <li>• Customer service</li>
                </ul>
                <div className='mt-4 p-4 rounded-xl bg-amber-500/10 border border-amber-500/30'>
                  <p className='text-amber-400 text-sm'>
                    We will never sell your personal information to third parties without your explicit consent.
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Data Protection */}
        <Card className='bg-white/5 backdrop-blur-sm border-white/10 mb-8'>
          <CardContent className='p-8'>
            <div className='flex items-start gap-4'>
              <Shield className='w-6 h-6 text-violet-400 flex-shrink-0 mt-1' />
              <div className='flex-1'>
                <h2 className='text-2xl font-bold text-white mb-4'>How Do We Protect Your Information?</h2>
                <p className='text-gray-400 mb-4'>
                  We implement a variety of security measures to maintain the safety of your personal information:
                </p>
                <ul className='space-y-3'>
                  <li className='flex items-start gap-2'>
                    <span className='text-emerald-400'>✓</span>
                    <span className='text-gray-300'>SSL encryption for all data transmissions</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-emerald-400'>✓</span>
                    <span className='text-gray-300'>Secure servers with regular security audits</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-emerald-400'>✓</span>
                    <span className='text-gray-300'>Limited access to personal information</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-emerald-400'>✓</span>
                    <span className='text-gray-300'>Regular security training for staff</span>
                  </li>
                  <li className='flex items-start gap-2'>
                    <span className='text-emerald-400'>✓</span>
                    <span className='text-gray-300'>Payment information is never stored after transactions</span>
                  </li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Cookies */}
        <Card className='bg-white/5 backdrop-blur-sm border-white/10 mb-8'>
          <CardContent className='p-8'>
            <div className='flex items-start gap-4'>
              <Cookie className='w-6 h-6 text-violet-400 flex-shrink-0 mt-1' />
              <div className='flex-1'>
                <h2 className='text-2xl font-bold text-white mb-4'>Cookies</h2>
                <p className='text-gray-400 mb-4'>
                  Tournest uses &quot;Cookies&quot; to identify the areas of our website that you have visited. 
                  A Cookie is a small piece of data stored on your computer or mobile device by your web browser.
                </p>
                <div className='space-y-3'>
                  <div className='p-4 rounded-xl bg-violet-500/10 border border-violet-500/20'>
                    <h3 className='text-violet-400 font-semibold mb-2'>Essential Cookies</h3>
                    <p className='text-gray-400 text-sm'>Required for platform functionality and cannot be disabled</p>
                  </div>
                  <div className='p-4 rounded-xl bg-pink-500/10 border border-pink-500/20'>
                    <h3 className='text-pink-400 font-semibold mb-2'>Analytics Cookies</h3>
                    <p className='text-gray-400 text-sm'>Help us understand usage patterns to improve our service</p>
                  </div>
                  <div className='p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20'>
                    <h3 className='text-emerald-400 font-semibold mb-2'>Preference Cookies</h3>
                    <p className='text-gray-400 text-sm'>Remember your settings and choices for a better experience</p>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Your Rights */}
        <Card className='bg-gradient-to-br from-emerald-900/30 to-teal-900/30 border-emerald-500/20 mb-8'>
          <CardContent className='p-8'>
            <div className='flex items-center gap-3 mb-6'>
              <UserCheck className='w-8 h-8 text-emerald-400' />
              <h2 className='text-2xl font-bold text-white'>Your Rights</h2>
            </div>
            
            <p className='text-gray-300 mb-6'>
              You have the right to request updates or corrections to the information Tournest collects. 
              You can contact us to:
            </p>
            
            <div className='grid sm:grid-cols-2 gap-6'>
              <div>
                <h3 className='text-emerald-400 font-semibold mb-2'>Access & Portability</h3>
                <p className='text-gray-400 text-sm'>
                  Request access to your personal data and receive it in a portable format.
                </p>
              </div>
              <div>
                <h3 className='text-emerald-400 font-semibold mb-2'>Correction</h3>
                <p className='text-gray-400 text-sm'>
                  Update or correct your personally identifiable information.
                </p>
              </div>
              <div>
                <h3 className='text-emerald-400 font-semibold mb-2'>Deletion</h3>
                <p className='text-gray-400 text-sm'>
                  Delete the personally identifiable information maintained about you on our systems.
                </p>
              </div>
              <div>
                <h3 className='text-emerald-400 font-semibold mb-2'>Communication Preferences</h3>
                <p className='text-gray-400 text-sm'>
                  Change your preferences with respect to communications and information you receive from us.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Children's Privacy */}
        <Card className='bg-amber-500/10 border-amber-500/30 mb-8'>
          <CardContent className='p-6'>
            <div className='flex items-start gap-4'>
              <AlertCircle className='w-6 h-6 text-amber-400 flex-shrink-0 mt-1' />
              <div>
                <h2 className='text-xl font-bold text-amber-400 mb-3'>Kids&apos; Privacy</h2>
                <p className='text-gray-300'>
                  We do not address anyone under the age of 18. We do not knowingly collect personally identifiable 
                  information from anyone under the age of 18. If You are a parent or guardian and You are aware that 
                  Your child has provided Us with Personal Data, please contact Us immediately.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Additional Information */}
        <Card className='bg-white/5 backdrop-blur-sm border-white/10 mb-8'>
          <CardContent className='p-8'>
            <h2 className='text-2xl font-bold text-white mb-6'>Additional Information</h2>
            
            <div className='space-y-6'>
              <div>
                <h3 className='text-lg font-semibold text-violet-400 mb-2'>Data Retention</h3>
                <p className='text-gray-400'>
                  We keep your information only so long as we need it to provide ShowStakr to you and fulfill the 
                  purposes described in this policy. When we no longer need to use your information, we&apos;ll either 
                  remove it from our systems or depersonalize it so that we can&apos;t identify you.
                </p>
              </div>

              <div>
                <h3 className='text-lg font-semibold text-violet-400 mb-2'>International Transfers</h3>
                <p className='text-gray-400'>
                  Information collected via our website may be transferred to our offices or personnel located throughout 
                  the world. By using our Service, you voluntarily consent to the trans-border transfer and hosting of such information.
                </p>
              </div>

              <div>
                <h3 className='text-lg font-semibold text-violet-400 mb-2'>Governing Law</h3>
                <p className='text-gray-400'>
                  This Privacy Policy is governed by the laws of Nigeria without regard to its conflict of laws provision. 
                  You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising 
                  between the parties under this Privacy Policy.
                </p>
              </div>

              <div>
                <h3 className='text-lg font-semibold text-violet-400 mb-2'>Policy Updates</h3>
                <p className='text-gray-400'>
                  We may change our Service and policies, and we may need to make changes to this Privacy Policy. 
                  We will notify you before we make changes and give you an opportunity to review them before they go into effect.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Contact */}
        <Card className='bg-gradient-to-r from-violet-500/10 to-pink-500/10 border-violet-500/20'>
          <CardContent className='p-6'>
            <div className='flex items-center gap-4'>
              <Mail className='w-6 h-6 text-violet-400' />
              <div>
                <h3 className='text-white font-semibold mb-1'>Privacy Questions?</h3>
                <p className='text-gray-400 text-sm'>
                  Don&apos;t hesitate to contact us if you have any questions about our Privacy Policy at{' '}
                  <a href='mailto:support@tournest.io' className='text-violet-400 hover:text-violet-300 transition-colors'>
                    support@tournest.io
                  </a>
                  {' '}or visit our{' '}
                  <Link href='/contact' className='text-violet-400 hover:text-violet-300 transition-colors'>
                    Contact Page
                  </Link>
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}